version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.yaml
    ports:
      - "8080:8080" # Map host port to container port
    volumes:
      - .:/app # Optional: bind your project directory for local development
    depends_on:
      - db # Ensure the database starts first
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=nba

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
